Repository Rohan-450/Digiconvert-Calculator, pull requests merged in 2024-01, with the labels that each got.

#15 Button disablity/enability feature added
  index.html
  script.js
  style.css
Labels: enhancement, apertre, medium

#22 Update script.js
  script.js
Labels: bug, apertre, easy

#25 Update script.js
  script.js
Labels: bug, apertre, easy

#27 Conversion facility added
  conversion.js
  index.html
  script.js
  style.css
Labels: bug, apertre, medium

#28 Updated the UI also added the favicon under issue number#6
  assets/favicon.png
  assets/icon1.png
  assets/icon2.png
  assets/icon3.png
  assets/icon4.png
  assets/icon5.png
  index.html
  script.js
  style.css
Labels: enhancement, apertre, medium

#31 added Button sound to current UI
  .vscode/settings.json
  index.html
  res/buttonclick.mp3
  res/equal.mp3
  res/mode.mp3
  script.js
  sound.js
Labels: enhancement, good first issue, apertre, medium

#35 fixed issue of changing modes
  script.js
Labels: bug, apertre, easy

#36 Updated conversions
  conversion_updated.js
  script.js
Labels: bug, apertre, hard

#40 Fixed floating point bug
  conversion_updated.js
Labels: bug, apertre, easy

#42 Disabled keyboard input
  index.html
Labels: bug, apertre, medium

#54 Updated the ui
  index.html
  script.js
  style.css
Labels: enhancement, apertre, medium

#56 Featuresandbugs/calculations del button and more
  script.js
Labels: enhancement, apertre, hard

#58 Update README.md
  README.md
Labels: apertre, easy

#60 Update README.md
  README.md
Labels: apertre, medium

#61 Add Footer In The Website
  assets/fb.png
  assets/ig.png
  assets/twt.png
  index.html
  style.css
Labels: apertre, easy

#64 Key hover
  index.html
  style.css
Labels: apertre, easy

#66 Fixed calc bugs and overall touchup
  index.html
  script.js
  style.css
Labels: apertre, hard
